import type { Professor, Course, Conference } from "./types"

export const mockProfessors: Professor[] = [
  {
    id: "1",
    name: "Dr. Carlos Mendoza",
    email: "carlos@example.com",
    bio: "Experto en transformación digital y estrategia empresarial con más de 20 años de experiencia.",
    specialty: "Transformación Digital",
    imageUrl: "/placeholder-user.jpg",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Dra. María García",
    email: "maria@example.com",
    bio: "Especialista en marketing digital y analytics. Consultora de empresas Fortune 500.",
    specialty: "Marketing Digital",
    imageUrl: "/placeholder-user.jpg",
    createdAt: new Date("2024-01-02"),
  },
  {
    id: "3",
    name: "Ing. Juan López",
    email: "juan@example.com",
    bio: "Ingeniero de software con especialidad en arquitectura en la nube.",
    specialty: "Tecnología Cloud",
    imageUrl: "/placeholder-user.jpg",
    createdAt: new Date("2024-01-03"),
  },
]

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "Transformación Digital Completa",
    description: "Aprende cómo transformar tu empresa en la era digital. Desde estrategia hasta implementación.",
    price: 199.99,
    duration: 480,
    thumbnailUrl: "/digital-transformation-course.png",
    videoUrl: "/sample-video.mp4",
    curriculum: [
      "Fundamentos de transformación digital",
      "Estrategia digital empresarial",
      "Tecnologías clave",
      "Implementación y gestión del cambio",
    ],
    professorId: "1",
    category: "Estrategia",
    level: "intermediate",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    title: "Marketing Digital Avanzado",
    description: "Domina las estrategias de marketing digital más efectivas para el 2024.",
    price: 149.99,
    duration: 360,
    thumbnailUrl: "/digital-marketing-course.png",
    videoUrl: "/sample-video.mp4",
    curriculum: ["SEO y SEM", "Social Media Marketing", "Email Marketing", "Analytics y ROI"],
    professorId: "2",
    category: "Marketing",
    level: "advanced",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "3",
    title: "Arquitectura en la Nube con AWS",
    description: "Curso completo de arquitectura en la nube usando AWS.",
    price: 249.99,
    duration: 540,
    thumbnailUrl: "/aws-cloud-architecture.jpg",
    videoUrl: "/sample-video.mp4",
    curriculum: [
      "Fundamentos de AWS",
      "EC2 y almacenamiento",
      "Bases de datos en la nube",
      "Seguridad y escalabilidad",
    ],
    professorId: "3",
    category: "Tecnología",
    level: "intermediate",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
]

export const mockConferences: Conference[] = [
  {
    id: "1",
    title: "Conferencia: El Futuro del Trabajo Remoto",
    description: "Una conversación abierta sobre cómo el trabajo remoto está transformando las empresas.",
    price: 29.99,
    scheduledDate: new Date("2024-12-15T18:00:00"),
    duration: 120,
    thumbnailUrl: "/remote-work-conference.jpg",
    videoUrl: "/sample-video.mp4",
    professorId: "1",
    category: "Conferencias",
    isLive: false,
    createdAt: new Date("2024-11-01"),
  },
  {
    id: "2",
    title: "Webinar: Tendencias en IA y Machine Learning",
    description: "Explora las últimas tendencias en Inteligencia Artificial y cómo están impactando los negocios.",
    price: 39.99,
    scheduledDate: new Date("2024-12-20T19:00:00"),
    duration: 90,
    thumbnailUrl: "/ai-machine-learning-webinar.jpg",
    videoUrl: "/sample-video.mp4",
    professorId: "3",
    category: "Conferencias",
    isLive: false,
    createdAt: new Date("2024-11-05"),
  },
]

export const mockTestimonials = [
  {
    id: "1",
    author: "Juan Pérez",
    role: "CEO, TechStartup",
    content: "Los cursos me ayudaron a transformar completamente nuestra estrategia digital.",
    rating: 5,
  },
  {
    id: "2",
    author: "Laura González",
    role: "Marketing Manager",
    content: "Excelente contenido. Las conferencias fueron muy inspiradoras.",
    rating: 5,
  },
  {
    id: "3",
    author: "Carlos Rodríguez",
    role: "Developer",
    content: "La calidad del contenido es profesional. Muy recomendado.",
    rating: 5,
  },
]
